### ISSUE TITLE
Staging tests

### ISSUE THREAD

**Issue by seromenho** [Fliplet/fliplet-widget-data-directory#1]
- [x] Doesn't update data on save widget
- [x] the list title and list description are the same class `list-title` - they should be separated so you can apply different styles
- [x] Title and Subtitle both appear as a title in the content area https://infinit.io/_/5qYqGC4
- [x] PADDING: Need additional padding-right for the subtitle https://infinit.io/_/HqRS7YX
- [x] Create layout with Data Directory
- [x] Disable Data Directory component from list of components

**Comment by tickettroll** [comment]
Also - the list title and list description are the same class `list-title` - they should be separated so you can apply different styles

[5:27]  
Also note - Title and Subtitle both appear as a title in the content area: https://infinit.io/_/5qYqGC4

**Comment by tickettroll** [comment]
PADDING: Need additional `padding-right` for the subtitle 

https://infinit.io/_/HqRS7YX

**Comment by tickettroll** [comment]
FILTER: The name of the current filter should appear in the search bar - confusing UI otherwise

https://infinit.io/_/uQZnxhs

**Comment by seromenho** [comment]
@hcarneiro this is all done right?
If not please reopen. Thanks
